// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://foeacfgpklrgtxvthyog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvZWFjZmdwa2xyZ3R4dnRoeW9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMjgwODUsImV4cCI6MjA2NzcwNDA4NX0.RqiP4_4i7BU5zHVHGRoslNkMocas8Q0103mMJAk7Pgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});